version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
    allow:
      - dependency-name: '@anthropic-ai/sdk'
      - dependency-name: '@anthropic-ai/claude-agent-sdk'
      - dependency-name: '@aws-sdk/client-bedrock-runtime'
      - dependency-name: '@aws-sdk/client-bedrock-agent-runtime'
      - dependency-name: '@azure/identity'
      - dependency-name: '@azure/openai-assistants'
      - dependency-name: '@fal-ai/client'
      - dependency-name: '@ibm-cloud/watsonx-ai'
      - dependency-name: '@modelcontextprotocol/sdk'
      - dependency-name: '@openai/agents'
      - dependency-name: 'openai'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - '*'
