import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    // Gradual migration from Jest - add directories here as they're migrated
    include: [
      'test/assertions/**/*.test.ts',
      'test/codeScans/**/*.test.ts',
      'test/matchers/**/*.test.ts',
      'test/database/**/*.test.ts',
      'test/site/**/*.test.ts',
      'test/testCase/**/*.test.ts',
      'test/validators/**/*.test.ts',
      'test/utils/**/*.test.ts',
      'test/models/**/*.test.ts',
      'test/app/**/*.test.ts',
      'test/globalConfig/**/*.test.ts',
      'test/integrations/**/*.test.ts',
      'test/external/**/*.test.ts',
      'test/progress/**/*.test.ts',
      'test/types/**/*.test.ts',
      'test/providers/bedrock/index.test.ts',
      'test/providers/azure/**/*.test.ts',
      'test/providers/azure.test.ts',
      'test/providers/anthropic/**/*.test.ts',
      'test/providers/openai/{responses,util}.test.ts',
      'test/providers/xai/**/*.test.ts',
      'test/providers/ollama.test.ts',
      'test/providers/truefoundry.test.ts',
      'test/providers/pythonCompletion*.test.ts',
      'test/providers/mcp/**/*.test.ts',
      'test/providers/functionCallbackUtils.test.ts',
      'test/providers/claude-agent-sdk.test.ts',
      'test/providers/cloudflare-ai.test.ts',
      'test/providers/browser.test.ts',
      'test/providers/groq/**/*.test.ts',
      'test/providers/hyperbolic/**/*.test.ts',
      'test/providers/hyperbolic.test.ts',
      'test/providers/openai/{chat,image,transcription}.test.ts',
      'test/prompts/**/*.test.ts',
      'test/python/**/*.test.ts',
      'test/commands/generate/**/*.test.ts',
      'test/providers/http.test.ts',
      'test/providers/{adaline.gateway,ai21,alibaba,fal,packageParser,scriptCompletion,togetherai,deepseek}.test.ts',
      'test/logger.test.ts',
      'test/cache.test.ts',
      'test/account.test.ts',
      'test/constants.test.ts',
      'test/monkeyPatchFetch.test.ts',
      'test/config-schema.test.ts',
      'test/envars.test.ts',
      'test/feedback.test.ts',
      'test/checkNodeVersion.test.ts',
      'test/csv.test.ts',
      'test/index.test.ts',
      'test/googleSheets.test.ts',
      'test/microsoftSharepoint.test.ts',
      'test/providers.slack.test.ts',
      'test/rateLimit.test.ts',
      'test/share.test.ts',
      'test/updates.test.ts',
      'test/tracing/**/*.test.ts',
      'test/util/**/*.test.ts',
      'test/providers/rubyCompletion.test.ts',
      'test/providers/websocket.test.ts',
      'test/providers/llamaApi.test.ts',
      'test/providers/shared.test.ts',
      'test/providers/snowflake.test.ts',
      'test/providers/webhook.test.ts',
      'test/providers/cometapi.test.ts',
      'test/providers/llama.test.ts',
      'test/providers/promptfooModel.test.ts',
      'test/providers/helicone.test.ts',
      'test/providers/aimlapi.test.ts',
      'test/providers/scriptBasedProvider.test.ts',
      'test/providers/replicate-image.test.ts',
      'test/providers/openai/defaults.test.ts',
      'test/providers/openai/embedding.test.ts',
      'test/providers/github/defaults.test.ts',
      'test/providers/github/index.test.ts',
      'test/providers/github/integration.test.ts',
      'test/providers/google/{util,vertex}.test.ts',
      'test/guardrails.test.ts',
      'test/table.test.ts',
      'test/redteam/constants.test.ts',
      'test/redteam/constants/metadata.test.ts',
      'test/redteam/constants/plugins.test.ts',
      'test/redteam/constants/strategies.test.ts',
      'test/redteam/metrics.test.ts',
      'test/redteam/riskScoring.test.ts',
      'test/redteam/sharedFrontend.test.ts',
      'test/redteam/types.test.ts',
      'test/redteam/util.test.ts',
      'test/redteam/strategies/base64.test.ts',
      'test/redteam/strategies/bestOfN.test.ts',
      'test/redteam/strategies/crescendo.test.ts',
      'test/redteam/strategies/custom.test.ts',
      'test/redteam/strategies/goat.test.ts',
      'test/redteam/strategies/hex.test.ts',
      'test/redteam/strategies/homoglyph.test.ts',
      'test/redteam/strategies/hydra.test.ts',
      'test/redteam/strategies/iterative.test.ts',
      'test/redteam/strategies/layer.test.ts',
      'test/redteam/strategies/leetspeak.test.ts',
      'test/redteam/strategies/mischievousUser.test.ts',
      'test/redteam/strategies/otherEncodings.test.ts',
      'test/redteam/strategies/promptInjections.test.ts',
      'test/redteam/strategies/retry.test.ts',
      'test/redteam/strategies/rot13.test.ts',
      'test/redteam/strategies/strategyId.test.ts',
      'test/redteam/remoteGeneration.test.ts',
      'test/redteam/graders.test.ts',
      'test/redteam/plugins/base.test.ts',
      'test/redteam/plugins/bias.test.ts',
      'test/redteam/plugins/competitors.test.ts',
      'test/redteam/plugins/contracts.test.ts',
      'test/redteam/plugins/custom.test.ts',
      'test/redteam/plugins/offTopic.test.ts',
      'test/redteam/plugins/overreliance.test.ts',
      'test/redteam/plugins/pii.test.ts',
      'test/redteam/plugins/policy.test.ts',
      'test/redteam/plugins/rbac.test.ts',
      'test/redteam/plugins/shellInjection.test.ts',
      'test/redteam/plugins/bola.test.ts',
      'test/redteam/plugins/bfla.test.ts',
      'test/redteam/plugins/imitation.test.ts',
      'test/redteam/plugins/wordplay.test.ts',
      'test/redteam/plugins/pluginId.test.ts',
      'test/redteam/plugins/pluginDocumentation.test.ts',
      'test/redteam/plugins/harmful/aligned.test.ts',
      'test/redteam/plugins/harmful/common.test.ts',
      'test/redteam/plugins/harmful/graders.test.ts',
      'test/redteam/plugins/harmful/unaligned.test.ts',
      'test/redteam/plugins/index.test.ts',
      'test/redteam/plugins/asciiSmuggling.test.ts',
      'test/redteam/plugins/crossSessionLeak.test.ts',
      'test/redteam/plugins/indirectPromptInjection.test.ts',
      'test/redteam/plugins/ferpa.test.ts',
      'test/redteam/plugins/mcp.test.ts',
      'test/redteam/plugins/financial/**/*.test.ts',
      'test/redteam/plugins/medical/**/*.test.ts',
      'test/redteam/commands/**/*.test.ts',
      'test/redteam/providers/**/*.test.ts',
      'test/redteam/extraction/**/*.test.ts',
      'test/commands/*.test.ts',
      'test/commands/eval/*.test.ts',
      'test/commands/mcp/**/*.test.ts',
      'test/server/**/*.test.ts',
      'test/evaluator*.test.ts',
      'test/evaluatorHelpers*.test.ts',
      'test/database.test.ts',
      'test/esm.test.ts',
      'test/fetch.test.ts',
      'test/globalConfig.test.ts',
      'test/main.test.ts',
      'test/onboarding.test.ts',
      'test/sagemaker.test.ts',
      'test/telemetry.test.ts',
      'test/providers.test.ts',
      'test/providers/*.test.ts',
      'test/providers/openai/*.test.ts',
      'test/providers/google/*.test.ts',
      'test/providers/bedrock/*.test.ts',
    ],
    // Exclude integration tests
    exclude: ['**/*.integration.test.ts', '**/node_modules/**'],
    // Use node environment (not jsdom) for backend tests
    environment: 'node',
    // Enable globals so we don't need to import describe/it/expect everywhere
    globals: true,
    // Setup files
    setupFiles: ['./vitest.setup.ts'],
    // Root directory
    root: '.',
    // Transform settings for ESM packages
    deps: {
      interopDefault: true,
    },
  },
});
